// Put each file's own hash in the URLs that point at it.
//
//   node scripts/stamp-media.js            say what is out of step
//   node scripts/stamp-media.js --write    rewrite the data files
//
// Everything in the bucket keeps its name when it is replaced, and that is
// deliberate: a still is matched to its episode by the name it shares with the
// video, a corrected subtitle is the same subtitle, and a better master of an
// episode is that episode. So replacing any of them leaves the address
// unchanged, and an unchanged address is one nobody re-fetches. Cloudflare
// holds the bucket for four hours, which at least expires; Stremio and Nuvio
// keep their own copies keyed on the URL with no expiry we can reach, so a
// viewer who has already opened an episode can keep the old file forever.
// The hash in the query fixes that and costs one extra round trip, once.
//
// Streams are included. Nothing is keyed on the stream URL — Stremio tracks
// watched and resume state against the video id, which is ours and permanent
// — and B2 answers a stamped URL exactly as it answers a bare one, ranges and
// all. `behaviorHints.filename` still carries the plain name for the client to
// show and for a player to read the container from.
//
// Most of data/ is generated by build-spinoffs.js, which stamps as it writes.
// Running this over those files should therefore report nothing, and that is
// the point of running it over them: a difference means the two have drifted.
// data/new-who.js is the one file no script produces. Its 239 overviews were
// written before the ledger existed and have never been moved into it, so it
// is edited by hand and this is the only thing that stamps it.

const fs = require('node:fs');
const path = require('node:path');
const { CDN, listing, shortHash } = require('./lib/bucket');

const ROOT = path.join(__dirname, '..');
const WRITE = process.argv.includes('--write');

const KINDS = 'jpg|srt|mkv|mp4|m4v';
const URL_RE = new RegExp(
  `${CDN.replace(/[.]/g, '\\.')}/([A-Za-z0-9_./-]+\\.(?:${KINDS}))(\\?v=[0-9a-f]+)?`, 'g');

const files = listing();
console.log(`${files.size} files in the bucket\n`);

let stamped = 0; let already = 0; const unknown = new Set(); let touched = 0;

for (const name of fs.readdirSync(path.join(ROOT, 'data')).filter((f) => f.endsWith('.js'))) {
  const file = path.join(ROOT, 'data', name);
  const before = fs.readFileSync(file, 'utf8');
  let changed = 0;

  const after = before.replace(URL_RE, (whole, rel, had) => {
    const f = files.get(rel);
    // A URL with no file behind it is a broken link, not a stamping problem.
    // Leave it exactly as it is and name it at the end; check-links.js is the
    // tool for deciding what to do about it.
    if (!f || !f.sha1) { unknown.add(rel); return whole; }
    const want = `?v=${shortHash(f.sha1)}`;
    if (had === want) { already += 1; return whole; }
    changed += 1; stamped += 1;
    return `${CDN}/${rel}${want}`;
  });

  if (!changed) continue;
  touched += 1;
  console.log(`  ${name.padEnd(26)} ${String(changed).padStart(4)} urls`);
  if (WRITE) fs.writeFileSync(file, after, 'utf8');
}

if (!touched) console.log('  every url already carries the right hash');
console.log(`\n${stamped} stamped, ${already} already correct`);
if (unknown.size) {
  console.log(`\n${unknown.size} urls point at nothing in the bucket:`);
  for (const u of [...unknown].slice(0, 10)) console.log(`   ${u}`);
}
if (touched && !WRITE) console.log('\ndry run. add --write.');
